Traceback (most recent call last):
  File "projet_SHINE_27_nov.py", line 4, in <module>
    import gym, gym_fastsim
ImportError: No module named gym
Traceback (most recent call last):
  File "projet_SHINE_27_nov.py", line 4, in <module>
    import gym, gym_fastsim
ImportError: No module named gym
Traceback (most recent call last):
  File "projet_SHINE_27_nov.py", line 4, in <module>
    import gym, gym_fastsim
ImportError: No module named gym
Traceback (most recent call last):
  File "projet_SHINE_27_nov.py", line 4, in <module>
    import gym, gym_fastsim
ImportError: No module named gym
Traceback (most recent call last):
  File "projet_SHINE_27_nov.py", line 4, in <module>
    import gym, gym_fastsim
ImportError: No module named gym
